### ISSUE TITLE
data preprocessing

### ISSUE THREAD

**Issue by weiyao1996** [janisgp/go_with_the_flows#1]
Hi, thanks for sharing your really nice work! Here I have a question about data preprocessing. Could you please indicate how long did the preprocess_ShapeNetAll.py take? I wonder how to set the n_processes and batch_size in it. In my case, it took more than two days without finishing, does it normal？By the way, is it possible to share your prepocessed data (.hdf5) via google drive or something? It would also be very helpful to cover only three categories (for example, airplane, chair, car).
Cheers,

**Comment by lmy1001** [comment]
Hi, I checked my code to prepare the dataset, unfortunately, I didn't save the scripts to generate it. And I went back to the [DPF link](https://github.com/Regenerator/dpf-nets) to find their configure, but I failed again. So based on my not clear memory, I may set n_processes =8, and batch_size=128. And trained for nearly one week for ShapeNetAll.  And I saved all the hdf5 files locally, but it's too large, I cannot share it through google drive, I feel sorry.

**Comment by janisgp** [comment]
Hi,

sorry for the reply response and thanks for your interest. The preprocessing of the dataset takes rather long (~1 week). You can run it with batch_size = 128 and n_processes = 8.

Alternatively, we also provide the preprocessed files (see README.md under "Download preprocessed datasets").

Let me know if this helps!

Best,
Janis

**Comment by janisgp** [comment]
@weiyao1996: Does this resolve your issue?

Best,
Janis

**Comment by weiyao1996** [comment]
Sure. Thank you so much.
Happy New Year!
